### PR TITLE
Hotfix/bootstrap variables

### PR DESCRIPTION
**Pull request by Ocramius**
Configuration to run KJSencha in a Jenkins instance (with php-template), travis tests and a small fix for the Bootstrap configuration

Ping @rovak

### CODE REVIEW

**Comment by Ocramius** [comment]
@Rovak managed to get this working on your CI? I just deployed it on mine (had to push this branch to my master for now since I'm a git-noob)

**Comment by Rovak** [comment]
Not yet, i will merge it anyways and get it up and running in the weekends.

**Comment by Rovak** [comment]
@Ocramius got it running => http://ci.razko.nl/job/KJSencha/

**Comment by Ocramius** [comment]
@Rovak awesome :+1:

**Pull request merged**
